{{- define "pebble.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pebble.fullname" . }}
  labels:
    {{- include "pebble.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.enableNodePorts }}
  type: NodePort
  {{- end }}
  selector:
    {{- include "pebble.selectorLabels" . | nindent 4 }}
  ports:
    - name: acme
      targetPort: acme
      port: 443
      {{- if .Values.service.enableNodePorts }}
      nodePort: {{ .Values.service.acmeNodePort }}
      {{- end }}
    - name: acme-mgmt
      targetPort: acme-mgmt
      port: 8080
      {{- if .Values.service.enableNodePorts }}
      nodePort: {{ .Values.service.acmeMgmtNodePort }}
      {{- end }}
{{- end }}

{{- include "pebble.service" . | fromYaml | merge .Values.merge.service | toYaml }}
