{{- define "pebble.configmap" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pebble.fullname" . }}
  labels:
    {{- include "pebble.labels" . | nindent 4 }}
data:
  # This configmap contains Pebble's configuration file and some certificate it
  # can use for its own HTTPS traffic, as well as the root certificate that
  # signed those.
  #
  pebble-config.json: |
    {{- .Values.pebble.config | toJson | nindent 4 }}

  # A root cert and key, for use by:
  # 1. Pebble's ACME server requires TLS communication: this root cert will
  #    create a leaf cert for Pebble to use in its installed namespace.
  #
  # 2. ACME client's speaking with Pebble need to trust this root cert in order
  #    to accept Pebble's leaf cert.
  #
  # NOTE: This root cert, or its leaf certs, are unrelated to the certs Pebble
  #       will provision as an ACME server. Pebble always recreates a new root
  #       cert on each startup and use it to create certs for the ACME clients.
  #       These temporary root certs are exposed through a REST API at /roots/0
  #       on the acme-mgmt port.
  #
  # ref: https://github.com/letsencrypt/pebble/tree/master/test/certs
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIIOvR7X+wFgKkwDQYJKoZIhvcNAQELBQAwIDEeMBwGA1UE
    AxMVbWluaWNhIHJvb3QgY2EgM2FmNDdiMCAXDTIwMDQyNjIzMDYxNloYDzIxMjAw
    NDI3MDAwNjE2WjAgMR4wHAYDVQQDExVtaW5pY2Egcm9vdCBjYSAzYWY0N2IwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCaoISLUOImo7vm7sGUpeycouDP
    TcJj6CxfCbvBsrlAg8ERGIph9H7TuDnTVk46pOaoxByGlwvvh4qR/Dled+G8NCt5
    s0r0yemY/fx1grm1TmcJRO+A1P5kx/M9hy+kVcyLRvPOnvo8Thj/4zvaJDh+pSjt
    5oAQvOHt9hYwGkkvSsZw12cTUuCsbypQ4lapDSeAjp3pNlqFcWmCvF9Ib3URDybN
    JWhY6yQQe54D2LxYqxCfYZjKhNbaxlNTlHu0Ujy75I/AdSjK6DljAZh0OimuQNEm
    FyXWvpnfyHbV5f0mMiXIOo2FY8izSD7cyFagmr0XvymCtxeDK1+MvT2pM+rXAgMB
    AAGjgYYwgYMwDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
    BgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBR0MgecNe4RY575
    qAtIt6zAjbBqLTAfBgNVHSMEGDAWgBR0MgecNe4RY575qAtIt6zAjbBqLTANBgkq
    hkiG9w0BAQsFAAOCAQEAjtGjoXGRG7586vyT3XcJBa8y9MOsDhQGOec23h40NJCn
    SPF28bmTIaWhB+Hv8G+Mkyf9Ov3L5L/mH0VGvZUkMAnSdT4vaMYGrTvMtYGS/8ew
    lPnlSJ3oO9Kz9zfOneoPDD1OGkV0Oq3wLn9cq6jQgItEeACsXNtaogXJxYhvxiV1
    1k/gjXmG9pvFpb0A1bw6apxGftIViDKrPR2P/pG3QAuLKywQiNxZ5odf3kvKdZmJ
    hLbu119My9XiiWhNegufcRNRNEnKJ5AQsBEwLEnD4oeIZmFvYVKOPjfWRV5qczVi
    mUPjtQv88HhlgX/lBVWJ2VONlFWVoOreZz4GkAm5bA==
    -----END CERTIFICATE-----

  root-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAmqCEi1DiJqO75u7BlKXsnKLgz03CY+gsXwm7wbK5QIPBERiK
    YfR+07g501ZOOqTmqMQchpcL74eKkfw5XnfhvDQrebNK9MnpmP38dYK5tU5nCUTv
    gNT+ZMfzPYcvpFXMi0bzzp76PE4Y/+M72iQ4fqUo7eaAELzh7fYWMBpJL0rGcNdn
    E1LgrG8qUOJWqQ0ngI6d6TZahXFpgrxfSG91EQ8mzSVoWOskEHueA9i8WKsQn2GY
    yoTW2sZTU5R7tFI8u+SPwHUoyug5YwGYdDoprkDRJhcl1r6Z38h21eX9JjIlyDqN
    hWPIs0g+3MhWoJq9F78pgrcXgytfjL09qTPq1wIDAQABAoIBAB0x7ZS4YtrU02eY
    8Of2JCS3BCdgETH35ljTZ6X87slllxB5R7eTCFdFU3W5t++OrxZyYMhwwIorV1iU
    /Of/TpnQZ90Eo0Rw0zBV1FMDqbi34vB3GZmDnby9nAmj+rTWllY9wU7j6W91d3bp
    GqXnbNtMp9uzR77hSu85JZtTezn4YzjIbHqd4+/+4xbOsla0wKXFjiCgYBy15a6a
    D92ypK/wyN0ghzyfNwIfnpqfHSUIOCogO8BClS3IV/wLci0hMIQlUkxm1MC7zsdN
    hLFy4I0bKzq5MA+F9Tv0S6MxUpB4vSGw0bQeZjfxuFCTcZ8XE0CMsByDW+nfGU5b
    Kmj75NECgYEAxP05uMVitQJh2Wi8kj5ufUIPA1OeGLdpuxXVkTm36Xsn4Jmv6NuU
    OaOqa7kNoYrpSlUjLBng6KetewxXWB3ykaftycutgXS/Cd8OoaHKmdBtado8m3tb
    shyTSG++8YLXVll4+Cn2DC6YHXJpq+OeDvFD+GTfgpa7kaWkBwswqZ0CgYEAyPKc
    CoMuzdLKl/+8pVAy2Yb8pcCd0+KC74BQDvusSGCJtDl4ophO2tbvt7pvQJ6PEBl+
    UDZdOohilWemG6wmswlAKsGn5L/I8946TF6r7l9CVBl9OAsSs2weZBNg5Ukqx5p+
    JryfDQfv+FJq3n1q3ECMzgj1KFMdG8khuJ71RgMCgYBLuXA7+BzGqmDE+38p1LgS
    jJdK1xT6OV96nJ0Zk4+AQGiG7W1y3R3wvlqfyGZWCBlACtRXeqc7qGGG4Kqe4/xA
    Q8akARj0n9VkTQvJ1HEWicnVnCAaQORx5owzl0lWe86dkg1vkGnWKv8sqrO2cOxs
    oBBZ5yUIhTsbdQpF7uZI/QKBgQCXOs7osnWE/UDvR84Hc+XxA8AcVmvxTKVR7fVS
    cWHlTpIUCrSZWZru45ehZDPaI/pzGVyQrXlYVdArtMe0R8kQMMQT6Y6bfyKTNgoV
    86HdUd+vP0eX5+15DsOIeXUQ2hHSCpkqOgZRXknhTtWTADxt6j6NyPwIDxT3FlXE
    hgz9VQKBgEVRIPV27tD97VfBy3PRLSSQqDcUS/LaUUXEv7H+l7VPWOffJKg+xcFJ
    nZ6akov9Z5vSDM7jjUStvaKQHV1QlqKGiVfdiLTFkwyC3B2IvxyAXWB/l+wckNP3
    SS3wHkUjXo/eWoK0wSC5yDooaklsXiXWNJtWwHiAsRqYFTUt4IQs
    -----END RSA PRIVATE KEY-----
{{- end }}

{{- include "pebble.configmap" . | fromYaml | merge .Values.merge.configmap | toYaml }}
