---
name: Test

on:
  pull_request:
  push:

jobs:
  test_pebble:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          # chartpress requires the full history
          fetch-depth: 0
      - uses: jupyterhub/action-k3s-helm@v0.2.2
        with:
          k3s-version: ""
          helm-version: ""
          metrics-enabled: false
          traefik-enabled: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run tests
        run: |
          helm lint pebble --values ci/ci-values.yaml
          helm lint pebble --strict --values ci/ci-values.yaml
          helm template pebble ./pebble --values ci/ci-values.yaml --validate
          helm install pebble ./pebble --values ci/ci-values.yaml --wait --timeout 60s
          helm test pebble
      - name: Emit report on success
        if: success()
        run: |
          kubectl get all --all-namespaces
      - name: Emit report on failure
        if: failure()
        run: |
          kubectl get all --all-namespaces
          kubectl logs pebble-test --all-containers --prefix
          kubectl logs pebble-coredns-test --all-containers --prefix
          kubectl logs deploy/pebble-coredns --all-containers --prefix
